### ISSUE TITLE
missing dependency on colcon-package-selection and colcon-ros

### ISSUE THREAD

**Issue by christianrauch** [Tacha-S/colcon-lint#3]
The package is missing dependencies on:
- `colcon-package-selection` in order to select specific packages via `--packages-select` (as per documentation)
- `colcon-ros` to actually discover standard ROS packages that use CMake

Depending on the support for other build systems, more dependencies are required.

**Comment by Tacha-S** [comment]
resolved in 7c4605e1e1970a21a13d1c8e3cb92a6e1fa4b039 (v0.3.1)
